#pragma once

#include "util/math.hpp"

namespace mp {

/**
 * State of the system
 * 
 * This is generated by the state estimator task and used
 * by the rest of the system to get current information about
 * the vehicle
 * 
 * State variables also shortened to:
 * `p` - position
 * `v` - (linear) velocity
 * `a` - (linear) acceleration
 * `w` (omega) - angular velocity
 * `q` - rotation quaternion
 * 
 * @note This is a public interface since this can also be provided
 * to external systems through the external api task
 */
struct state_s {
    // Position of the center of mass (CoM) of the vehicle in
    // the global (inertial) reference frame
    vector3f position {0, 0, 0};
    // (Linear) velocity of the CoM (= d/dt(position))
    vector3f velocity {0, 0, 0};
    // (Linear) acceleration of the CoM in the global reference frame
    vector3f acceleration {0, 0, 0};
    // Angular acceleration vector in the local rotating (non-inertial) reference frame
    vector3f angular_velocity {0, 0, 0};
    // Quaternion which maps the local frame to the global frame
    quaternionf rotationq {1, 0, 0, 0};
    
    // Current estimation of gyroscope drift
    // TODO: Move into a separate struct and use this only for kinematics
    vector3f gyroscope_drift;
};

/**
 * State estimation algorithm interface
 */
class state_estimator {

public:
    /**
     * Get the current state
     * @todo Rename `state_s` to `kinematics_s` and
     * rename this to `get_kinematics` and separate sensor
     * stuff like gyro drift
     */
    virtual state_s get_state() const noexcept = 0;
};

}